model_params:
  name: 'MSSIMVAE'
  in_channels: 3
  latent_dim: 16 

data_params:
  data_path: "Data/lunar-lander/data_comb_third_vae"
  train_batch_size: 32
  val_batch_size:  32
  patch_size: 64
  num_workers: 4


exp_params:
  LR: 0.005
  weight_decay: 0.0005
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  gpus: [0]
  max_epochs: 100

logging_params:
  save_dir: "logs/BCE_sum_VAE/"
  name: 'bceVAE'