
model_params:
  name: 'BetaVAE'
  in_channels: 3
  latent_dim: 75
  loss_type: 'H'
  beta: 10.

data_params:
  data_path: "Data/lunar_Data/"
  train_batch_size: 16
  val_batch_size:  16
  patch_size: 64
  num_workers: 4


exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  gpus: [0]
  max_epochs: 30

logging_params:
  save_dir: "logs/"
  name: 'BetaVAE'